export const showcaseProducts = [
  {
    name: "Country Onion",
    origin: "Cameroon",
    description: "Ground country onion spice, Wt 4 oz",
    image: "/images/country_onion.png",
  },
  {
    name: "Fried Peanuts",
    origin: "Cameroon",
    description: "Roasted peanuts, Wt 0.5 L",
    image: "/images/fried_peanuts.png",
  },
  {
    name: "Grey White Millet",
    origin: "Cameroon",
    description: "Whole grain millet, Wt 2 oz",
    image: "/images/grey_white_millet.png",
  },
  {
    name: "Moringa Powder",
    origin: "Cameroon",
    description: "Moringa leaves powder, Wt 8 oz",
    image: "/images/moringa_powder.png",
  },
  {
    name: "Pepper Soup Spices",
    origin: "Cameroon",
    description: "Secret blend spices, Wt 6 oz",
    image: "/images/pepper_soup_spices.png",
  },
  {
    name: "Kalaba Chalk",
    origin: "Cameroon",
    description: "Kaolin clay, Wt 8 oz",
    image: "/images/karaba_chalk.png",
  },
  {
    name: "Eru/Okazi",
    origin: "Cameroon",
    description: "Dried eru leaves, Wt 6 oz",
    image: "/images/chopped_eru_leaves.png",
  },
  {
    name: "Ginger Powder",
    origin: "Cameroon",
    description: "Premium ground ginger",
    image: "/images/ginger.png",
  },
  // Added products below (matched to existing images in public/images)
  {
    name: "Njangsa",
    origin: "Cameroon",
    description: "Aromatic spice seeds used in traditional dishes",
    image: "/images/njangsa.png",
  },
  {
    name: "Suya Spice",
    origin: "Nigeria",
    description: "Classic suya seasoning blend",
    image: "/images/suya_spice.png",
  },
  {
    name: "Okazi (Fumbua)",
    origin: "Congo",
    description: "Dried okazi leaves — fumbua",
    image: "/images/Okazi_fumbua.png",
  },
  {
    name: "Activated Charcoal",
    origin: "Ghana",
    description: "Food-grade activated charcoal powder",
    image: "/images/activated_charcoal.png",
  },
  {
    name: "Cameroon Hot Pepper",
    origin: "Cameroon",
    description: "Ground Cameroon hot pepper",
    image: "/images/cameroon_hot_pepper.png",
  },
  {
    name: "Cassava Fufu",
    origin: "Cameroon",
    description: "Premium cassava fufu flour",
    image: "/images/cassava_fufu.png",
  },
  {
    name: "Baobab Powder",
    origin: "Cameroon",
    description: "Nutritious baobab fruit powder",
    image: "/images/baobab_powder.png",
  },
  {
    name: "Candied Peanut",
    origin: "Cameroon",
    description: "Sweet candied peanuts bottle",
    image: "/images/candied_peanut.png",
  },
  {
    name: "Jadida Margarine",
    origin: "Morocco",
    description: "Tartines & cuisson margarine",
    image: "/images/jadida.png",
  },
  {
    name: "Fried Corn & Peanut",
    origin: "Cameroon",
    description: "Crispy fried corn with peanuts",
    image: "/images/fried_corn_or_peanut.png",
  },
  {
    name: "Mbongo Tchobi Spice",
    origin: "Cameroon",
    description: "Traditional black soup spice blend",
    image: "/images/mbongo_spice.png",
  },
  {
    name: "Hot Red Pepper",
    origin: "Cameroon",
    description: "Fine ground red pepper 8oz",
    image: "/images/red_hot_pepper.jpeg",
  },
  {
    name: "Maggi Cubes",
    origin: "Cameroon",
    description: "Seasoning cubes pack",
    image: "/images/maggi.png",
  },
  {
    name: "Ground Ogbono",
    origin: "Nigeria",
    description: "Ground ogbono seeds",
    image: "/images/ground_ogbono.png",
  },
  {
    name: "Whole Cloves",
    origin: "Cameroon",
    description: "Aromatic whole cloves in shaker bottle",
    image: "/images/Whole-cloves.png",
  },
  {
    name: "Tartina Spread",
    origin: "Cameroon",
    description: "Chocolate hazelnut spread",
    image: "/images/tartina.png",
  },
  {
    name: "Peau de Lune Lotion",
    origin: "Cote d'Ivoire",
    description: "Beauty lotion (duo bottles)",
    image: "/images/peau_de_lune.png",
  },
  {
    name: "Natural Honey",
    origin: "Cameroon",
    description: "Pure natural honey bottle",
    image: "/images/natural_honey.png",
  },
  {
    name: "Red Palm Oil",
    origin: "Cameroon",
    description: "Premium red palm oil, 5L jug",
    image: "/images/red_palm_oil.jpg",
  },
  {
    name: "TomTom Candy",
    origin: "Nigeria",
    description: "Strong menthol flavored candy",
    image: "/images/tom_tom.png",
  },
  {
    name: "Anise Seeds",
    origin: "Cameroon",
    description: "Whole anise seeds for rich flavor",
    image: "/images/anise_seeds.png",
  },
  {
    name: "Coconut Sweet",
    origin: "Cameroon",
    description: "Crunchy coconut sweet snacks",
    image: "/images/coconut-sweet.png",
  },
  {
    name: "Special Pamplemousse",
    origin: "Cameroon",
    description: "Sparkling grapefruit beverage",
    image: "/images/Special-Pamplemousse.png",
  },
  {
    name: "Top Grenadine Soda",
    origin: "Cameroon",
    description: "Refreshing grenadine flavored soda",
    image: "/images/Top-grenadine.png",
  },
  {
    name: "Top Ananas Soda",
    origin: "Cameroon",
    description: "Tropical pineapple flavored soda",
    image: "/images/top-anamas.png",
  },
  {
    name: "Yellow Garri",
    origin: "Cameroon",
    description: "Yellow garri cassava flakes",
    image: "/images/yellow_garri.png",
  },
  {
    name: "Djino Soda",
    origin: "Cameroon",
    description: "Sparkling fruit soda drink",
    image: "/images/Djino.png",
  },
  {
    name: "Whole Crayfish (Njanga)",
    origin: "Cameroon",
    description: "Dried whole crayfish pack",
    image: "/images/whole_crayfish.png",
  },
  {
    name: "Mambo Chocolate",
    origin: "Congo",
    description: "Creamy milk chocolate wafers",
    image: "/images/mambo.png",
  },
  {
    name: "Turmeric Powder",
    origin: "India",
    description: "Bright, aromatic turmeric powder",
    image: "/images/turmeric.png",
  },
];
